matrix:
  include:
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, libcurl4-gnutls-dev]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, libcurl4-gnutls-dev]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Release, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, libcurl4-gnutls-dev]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, ASAN=ON, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, libcurl4-gnutls-dev]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, TSAN=ON, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, binutils, libcurl4-gnutls-dev]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, UBSAN=ON, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, ninja-build, libcurl4-gnutls-dev]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON, NINJA=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, ninja-build, libcurl4-gnutls-dev]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Release, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON, NINJA=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8 main
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: [clang-8, libstdc++-8-dev, libcurl4-gnutls-dev]
      env: [CXX=clang++-8, CC=clang-8, BUILD_TYPE=Release, DEFAULT_COMPILER=clang, WILL_COMPILE_CODE=ON, DEPLOY=ON, PIP=pip]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8 main
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: [clang-8, libstdc++-8-dev, libcurl4-gnutls-dev]
      env: [CXX=clang++-8, CC=clang-8, BUILD_TYPE=Debug, DEFAULT_COMPILER=clang, WILL_COMPILE_CODE=ON, DEPLOY=ON, PIP=pip]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8 main
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: [clang-8, libstdc++-8-dev, libcurl4-gnutls-dev]
      env: [CXX=clang++-8, CC=clang-8, BUILD_TYPE=Debug, DEFAULT_COMPILER=clang, WILL_COMPILE_CODE=ON, DEPLOY=ON, PIP=pip, ASAN=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8 main
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: [clang-8, libstdc++-8-dev, libcurl4-gnutls-dev]
      env: [CXX=clang++-8, CC=clang-8, BUILD_TYPE=Debug, DEFAULT_COMPILER=clang, WILL_COMPILE_CODE=ON, DEPLOY=ON, PIP=pip, TSAN=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8 main
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: [clang-8, libstdc++-8-dev]
      env: [CXX=clang++-8, CC=clang-8, BUILD_TYPE=Debug, DEFAULT_COMPILER=clang, WILL_COMPILE_CODE=ON, DEPLOY=ON, PIP=pip, UBSAN=ON]
    - os: osx
      osx_image: xcode10.2
      sudo: true
      env: [BUILD_TYPE=Release,
            CLANG_VERSION=clang-8,
            CC=/usr/local/opt/llvm@8/bin/clang,
            CXX=/usr/local/opt/llvm@8/bin/clang++,
            LD=ld.lld,
            AR=llvm-ar,
            RANLIB=llvm-ranlib,
            LDFLAGS=-L/usr/local/opt/llvm@8/lib,
            CPPFLAGS=-I/usr/local/opt/llvm@8/include,
            PIP=pip3,
            WILL_COMPILE_CODE=ON, DEFAULT_COMPILER=clang]
      addons:
        homebrew:
          packages: [cmake,ninja,llvm@8,python3]
          update: true
    - os: osx
      osx_image: xcode10.2
      sudo: true
      env: [BUILD_TYPE=Debug,
            CLANG_VERSION=clang-8,
            CC=/usr/local/opt/llvm@8/bin/clang,
            CXX=/usr/local/opt/llvm@8/bin/clang++,
            LD=ld.lld,
            AR=llvm-ar,
            RANLIB=llvm-ranlib,
            LDFLAGS=-L/usr/local/opt/llvm@8/lib,
            CPPFLAGS=-I/usr/local/opt/llvm@8/include,
            PIP=pip3,
            WILL_COMPILE_CODE=ON, DEFAULT_COMPILER=clang]
      addons:
        homebrew:
          packages: [cmake,ninja,llvm@8,python3]
          update: true


install:
  - |
    source ${TRAVIS_BUILD_DIR}/scripts/travis_install.sh

script:
  - |
    source ${TRAVIS_BUILD_DIR}/scripts/travis_build.sh
