matrix:
  include:
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Release, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, ASAN=ON, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, TSAN=ON, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, binutils]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, UBSAN=ON, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, ninja-build]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Debug, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON, NINJA=ON]
    - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [g++-8, ninja-build]
      env: [CXX=g++-8, CC=gcc-8, WILL_COMPILE_CODE=ON, BUILD_TYPE=Release, DEFAULT_COMPILER=gcc, PIP=pip, WILL_COMPILE_CODE=ON, NINJA=ON]
     - os: linux
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8 main
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: [clang-8, libstdc++-8-dev]
      env: [CXX=clang++-8, CC=clang-8, BUILD_TYPE=Release, DEFAULT_COMPILER=clang, WILL_COMPILE_CODE=ON, DEPLOY=ON, PIP=pip]

install:
  - |
    source ${TRAVIS_BUILD_DIR}/scripts/travis_install.sh

script:
  - |
    source ${TRAVIS_BUILD_DIR}/scripts/travis_build.sh
