version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      GENERATOR: Visual Studio 15 2017
      BUILD_TYPE: Debug

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: x64
      GENERATOR: Visual Studio 15 2017
      BUILD_TYPE: Release

init:
  - mkdir C:\Users\appveyor\.conda
  - call C:\\Miniconda3-x64\Scripts\activate.bat
  - conda install -c conda-forge curl -y
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - where cmake
  - ps: Invoke-WebRequest -Uri https://cmake.org/files/v3.14/cmake-3.14.3-win64-x64.zip -OutFile cmake.zip
  - 7z x cmake.zip -o"c:\Program Files (x86)\CMake\" -y
  - ps: Get-ChildItem "C:\Program Files (x86)\CMake\"
  - ps: Get-ChildItem "C:\Program Files (x86)\CMake\cmake-3.14.3-win64-x64\"
  - ps: Copy-Item -Path "C:\Program Files (x86)\CMake\cmake-3.14.3-win64-x64\*" -Destination "C:\Program Files (x86)\CMake\" -Force -Recurse
  - ps: Get-ChildItem "C:\Program Files (x86)\CMake\"
  - ps: Get-ChildItem "C:\Program Files (x86)\CMake\cmake-3.14.3-win64-x64\"
  - rm cmake.zip
  - cmake --version
  - msbuild /version

before_build:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ../ -G "%GENERATOR%" -A %platform% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"

build_script:
  - cmake --build . --target mmbot-test --config %BUILD_TYPE% -- /verbosity:minimal /maxcpucount:3
  - cmake --build . --target mmbot --config %BUILD_TYPE% -- /verbosity:minimal /maxcpucount:3
  - cd bin && cd %BUILD_TYPE% && ls
  - ps: |
      $filePattern = '*-test.exe'
      foreach ($file in get-ChildItem $filePattern)
      {
        $var = $file.name
        & cmd /c "$var --reporters=xml --out=$var-result.xml -s 2>&1"
      }
      ls

on_failure:
  - curl -s https://report.ci/annotate.py | python - --tool msvc --input build.log

on_finish:
  # Framework with autodetection
  - ps: |
      ls
      $string = "$env:GENERATOR-$env:BUILD_TYPE"
      echo $string
      $string = $string -replace ' ', '-'
      echo $string
      Invoke-WebRequest -Uri https://report.ci/upload.py -OutFile upload.py
      python upload.py -n "Doctest [appveyor $($string)]" --include='*.xml' --framework=doctest --merge .*